# 此页内容已被童年是个风筝（sctop）更新过
# 原内容请自行fork原项目：https://github.com/kaeyleo/jekyll-theme-H2O
# Site settings 配置站点
title: '童年是个风筝的博客'
description: '小名宝仔，Scratch语言爱好者，河源市第一小学五年级小学狗一名。现在致力于管理网站和写博客文章。'  # 搜索引擎蜘蛛捕捉的内容
keyword: '童年是个风筝, 童年是个风筝的博客, '
url: 'http://www.zhangqirun.cn/' # your host
link: true

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links  导航链接
nav:
  home: '/'
  tags: '/tags.html'
  VistalStudio: '/VisualStudio2017.html'
  updatelog: '/UpdateLog.html'

# Author 配置博主信息
# author真名 nickname小名 bio简介 avatar头像
author: '张颀润'
nickname: '宝仔'
bio: '广东省河源市第一小学五年级的小学狗一名，热爱写博客&搞东西。爱PR，爱Scratch，爱b站和many things。现在致力于管理网站和写博客文章，对大千世界有着自己的见解。同学们中间的电脑高手（滑稽）。'
avatar: '/assets/img/profile.jpg'


# Search  搜索
search: true

# Night mode  夜间模式
nightMode: true

# Comments  评论（disqus，需要翻墙）
# disqus开启关闭 disqus_url评论js地址
disqus: false
disqus_url: ''

# Share  分享
# 第一个是是否开启，第二个是分享的渠道
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default  粉色或者默认（蓝色）

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
# 文章底纹（当文章没有底纹图片时），中英文对照：
# circuitBoard 电路
# overlappingCircles 圆环
# food 吃货日常：肯打鸡
# glamorous 土豪必备：钻石
# ticTacToe 圈圈叉叉
# seaOfClouds 中国风：云海
# 默认为ciruitBoard
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/sctop'

# Tags 设置标签
# whether or not display recommend-tags on the sidebar
# 是否在侧边栏上显示标签
recommend-tags: true
# a tag will be recommended if the size of it is more than this value
# 如果标签的大小大于此值，则建议使用该标记。
recommend-condition-size: 12

# Build settings  生成设置
# paginate 每一页显示的文章个数  paginate_path 设置文章每一页显示的个数  exclude 不生成的文件/文件夹，需要绝对路径，文件夹直接写文件夹名字，文件名需带后缀
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS订阅
RSS: true

# Plugins
gems: [jekyll-paginate]

# 童年是个风筝添加内容：

# 网站管理&统计
# ture一律启用，false一律关闭
baidutjopen: 'true' # 百度统计代码是否启用
baidutj: 'https://hm.baidu.com/hm.js?96736cf6e5a2a329a74ae83047b92073' # 百度统计代码js网址（hm.src片段）

bingtjopen: 'true' # 必应网站管理是否启用
bingtj: '60C8EBAF57EF518899B5C5D16D8D2ADB' # 必应网站管理（content片段）

baidusszyptautolink: 'true' # 百度搜索资源平台自动提交链接是否开启

360webscanopen: 'big' # 360网站安全是否打开（big表示大图标，small表示小图标，false表示不开启）
360webscanurl: 'zhangqirun.cn' # 要检测的网址

# 友情链接
links:
  空白代刷站: 'http://likebuying.top/'
  Cloudflare云服务: 'https://www.cloudflare.com/'